#ifndef MULTITHREADING_LABS_OPENCL_H
#define MULTITHREADING_LABS_OPENCL_H

#define CL_HPP_MINIMUM_OPENCL_VERSION 120
#define CL_HPP_TARGET_OPENCL_VERSION 120
#define CL_HPP_CL_1_2_DEFAULT_BUILD
#define CL_HPP_ENABLE_EXCEPTIONS

#include <CL/cl2.hpp>

#endif /* OpenCL.h */
